/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StepsRouteImport } from './routes/steps'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PokemonRouteRouteImport } from './routes/pokemon/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonIndexRouteImport } from './routes/pokemon/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as hiddenFolderFirstLevelRouteImport } from './routes/(hidden-folder)/first-level'
import { Route as PokemonIdRouteRouteImport } from './routes/pokemon/$id/route'
import { Route as PokemonIdIndexRouteImport } from './routes/pokemon/$id/index'
import { Route as hiddenFolderLayoutsVisibleLayoutRouteImport } from './routes/(hidden-folder)/layouts/visibleLayout'
import { Route as hiddenFolderLayoutsHiddenLayoutRouteImport } from './routes/(hidden-folder)/layouts/_hiddenLayout'
import { Route as hiddenFolderLayoutsVisibleLayoutFooRouteImport } from './routes/(hidden-folder)/layouts/visibleLayout/foo'
import { Route as hiddenFolderLayoutsVisibleLayoutBarRouteImport } from './routes/(hidden-folder)/layouts/visibleLayout/bar'
import { Route as hiddenFolderLayoutsHiddenLayoutFooRouteImport } from './routes/(hidden-folder)/layouts/_hiddenLayout/foo'
import { Route as hiddenFolderLayoutsHiddenLayoutBarRouteImport } from './routes/(hidden-folder)/layouts/_hiddenLayout/bar'

const StepsRoute = StepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonRouteRoute = PokemonRouteRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PokemonRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const hiddenFolderFirstLevelRoute = hiddenFolderFirstLevelRouteImport.update({
  id: '/(hidden-folder)/first-level',
  path: '/first-level',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIdRouteRoute = PokemonIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PokemonRouteRoute,
} as any)
const PokemonIdIndexRoute = PokemonIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PokemonIdRouteRoute,
} as any)
const hiddenFolderLayoutsVisibleLayoutRoute =
  hiddenFolderLayoutsVisibleLayoutRouteImport.update({
    id: '/(hidden-folder)/layouts/visibleLayout',
    path: '/layouts/visibleLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const hiddenFolderLayoutsHiddenLayoutRoute =
  hiddenFolderLayoutsHiddenLayoutRouteImport.update({
    id: '/(hidden-folder)/layouts/_hiddenLayout',
    path: '/layouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const hiddenFolderLayoutsVisibleLayoutFooRoute =
  hiddenFolderLayoutsVisibleLayoutFooRouteImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)
const hiddenFolderLayoutsVisibleLayoutBarRoute =
  hiddenFolderLayoutsVisibleLayoutBarRouteImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)
const hiddenFolderLayoutsHiddenLayoutFooRoute =
  hiddenFolderLayoutsHiddenLayoutFooRouteImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)
const hiddenFolderLayoutsHiddenLayoutBarRoute =
  hiddenFolderLayoutsHiddenLayoutBarRouteImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon': typeof PokemonRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/steps': typeof StepsRoute
  '/pokemon/$id': typeof PokemonIdRouteRouteWithChildren
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/pokemon/$id/': typeof PokemonIdIndexRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/steps': typeof StepsRoute
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pokemon': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/pokemon/$id': typeof PokemonIdIndexRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemon': typeof PokemonRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/steps': typeof StepsRoute
  '/pokemon/$id': typeof PokemonIdRouteRouteWithChildren
  '/(hidden-folder)/first-level': typeof hiddenFolderFirstLevelRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/(hidden-folder)/layouts/_hiddenLayout': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/(hidden-folder)/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/pokemon/$id/': typeof PokemonIdIndexRoute
  '/(hidden-folder)/layouts/_hiddenLayout/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/(hidden-folder)/layouts/_hiddenLayout/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/(hidden-folder)/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/(hidden-folder)/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemon'
    | '/login'
    | '/profile'
    | '/search'
    | '/steps'
    | '/pokemon/$id'
    | '/first-level'
    | '/dashboard'
    | '/settings'
    | '/pokemon/'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/pokemon/$id/'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/search'
    | '/steps'
    | '/first-level'
    | '/dashboard'
    | '/settings'
    | '/pokemon'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/pokemon/$id'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  id:
    | '__root__'
    | '/'
    | '/pokemon'
    | '/_authenticated'
    | '/login'
    | '/profile'
    | '/search'
    | '/steps'
    | '/pokemon/$id'
    | '/(hidden-folder)/first-level'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/pokemon/'
    | '/(hidden-folder)/layouts/_hiddenLayout'
    | '/(hidden-folder)/layouts/visibleLayout'
    | '/pokemon/$id/'
    | '/(hidden-folder)/layouts/_hiddenLayout/bar'
    | '/(hidden-folder)/layouts/_hiddenLayout/foo'
    | '/(hidden-folder)/layouts/visibleLayout/bar'
    | '/(hidden-folder)/layouts/visibleLayout/foo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonRouteRoute: typeof PokemonRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  StepsRoute: typeof StepsRoute
  hiddenFolderFirstLevelRoute: typeof hiddenFolderFirstLevelRoute
  hiddenFolderLayoutsHiddenLayoutRoute: typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  hiddenFolderLayoutsVisibleLayoutRoute: typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon': {
      id: '/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof PokemonRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(hidden-folder)/first-level': {
      id: '/(hidden-folder)/first-level'
      path: '/first-level'
      fullPath: '/first-level'
      preLoaderRoute: typeof hiddenFolderFirstLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdRouteRouteImport
      parentRoute: typeof PokemonRouteRoute
    }
    '/pokemon/$id/': {
      id: '/pokemon/$id/'
      path: '/'
      fullPath: '/pokemon/$id/'
      preLoaderRoute: typeof PokemonIdIndexRouteImport
      parentRoute: typeof PokemonIdRouteRoute
    }
    '/(hidden-folder)/layouts/visibleLayout': {
      id: '/(hidden-folder)/layouts/visibleLayout'
      path: '/layouts/visibleLayout'
      fullPath: '/layouts/visibleLayout'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hidden-folder)/layouts/_hiddenLayout': {
      id: '/(hidden-folder)/layouts/_hiddenLayout'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hidden-folder)/layouts/visibleLayout/foo': {
      id: '/(hidden-folder)/layouts/visibleLayout/foo'
      path: '/foo'
      fullPath: '/layouts/visibleLayout/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutFooRouteImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutRoute
    }
    '/(hidden-folder)/layouts/visibleLayout/bar': {
      id: '/(hidden-folder)/layouts/visibleLayout/bar'
      path: '/bar'
      fullPath: '/layouts/visibleLayout/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutBarRouteImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout/foo': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/foo'
      path: '/foo'
      fullPath: '/layouts/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutFooRouteImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout/bar': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/bar'
      path: '/bar'
      fullPath: '/layouts/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutBarRouteImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutRoute
    }
  }
}

interface PokemonIdRouteRouteChildren {
  PokemonIdIndexRoute: typeof PokemonIdIndexRoute
}

const PokemonIdRouteRouteChildren: PokemonIdRouteRouteChildren = {
  PokemonIdIndexRoute: PokemonIdIndexRoute,
}

const PokemonIdRouteRouteWithChildren = PokemonIdRouteRoute._addFileChildren(
  PokemonIdRouteRouteChildren,
)

interface PokemonRouteRouteChildren {
  PokemonIdRouteRoute: typeof PokemonIdRouteRouteWithChildren
  PokemonIndexRoute: typeof PokemonIndexRoute
}

const PokemonRouteRouteChildren: PokemonRouteRouteChildren = {
  PokemonIdRouteRoute: PokemonIdRouteRouteWithChildren,
  PokemonIndexRoute: PokemonIndexRoute,
}

const PokemonRouteRouteWithChildren = PokemonRouteRoute._addFileChildren(
  PokemonRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface hiddenFolderLayoutsHiddenLayoutRouteChildren {
  hiddenFolderLayoutsHiddenLayoutBarRoute: typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  hiddenFolderLayoutsHiddenLayoutFooRoute: typeof hiddenFolderLayoutsHiddenLayoutFooRoute
}

const hiddenFolderLayoutsHiddenLayoutRouteChildren: hiddenFolderLayoutsHiddenLayoutRouteChildren =
  {
    hiddenFolderLayoutsHiddenLayoutBarRoute:
      hiddenFolderLayoutsHiddenLayoutBarRoute,
    hiddenFolderLayoutsHiddenLayoutFooRoute:
      hiddenFolderLayoutsHiddenLayoutFooRoute,
  }

const hiddenFolderLayoutsHiddenLayoutRouteWithChildren =
  hiddenFolderLayoutsHiddenLayoutRoute._addFileChildren(
    hiddenFolderLayoutsHiddenLayoutRouteChildren,
  )

interface hiddenFolderLayoutsVisibleLayoutRouteChildren {
  hiddenFolderLayoutsVisibleLayoutBarRoute: typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  hiddenFolderLayoutsVisibleLayoutFooRoute: typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

const hiddenFolderLayoutsVisibleLayoutRouteChildren: hiddenFolderLayoutsVisibleLayoutRouteChildren =
  {
    hiddenFolderLayoutsVisibleLayoutBarRoute:
      hiddenFolderLayoutsVisibleLayoutBarRoute,
    hiddenFolderLayoutsVisibleLayoutFooRoute:
      hiddenFolderLayoutsVisibleLayoutFooRoute,
  }

const hiddenFolderLayoutsVisibleLayoutRouteWithChildren =
  hiddenFolderLayoutsVisibleLayoutRoute._addFileChildren(
    hiddenFolderLayoutsVisibleLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonRouteRoute: PokemonRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  StepsRoute: StepsRoute,
  hiddenFolderFirstLevelRoute: hiddenFolderFirstLevelRoute,
  hiddenFolderLayoutsHiddenLayoutRoute:
    hiddenFolderLayoutsHiddenLayoutRouteWithChildren,
  hiddenFolderLayoutsVisibleLayoutRoute:
    hiddenFolderLayoutsVisibleLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
